var hello = [
	"Hi there 👋",
	"Hi!",
	"Hidey-ho, neighbor!",
	"Salutations,",
	"Hey Y'all,",
	"Heya,",
	"Hola!",
	"Aloha!",
	"Sup",
	"👋",
	"✌️",
	"Hey ✌️"
];

var hello_id = Math.floor(Math.random() * hello.length);
$('h1').html(hello[hello_id]);

var job = [
	"UX Designer",
	"Product Designer",
	"UI/UX Designer",
	"UX/UI Designer",
	"UI Designer",
	"Creative Technologist",
	"Creative Visionary",
	"Thought Leader",
	"Design Mentor",
	"Graphic Designer",
	"Digital Artist",
	"Design Ninja",
	"Interaction Designer",
	"Motion Designer",
	"Design Unicorn",
	"Design Rockstar",
	"Rockstar Designer",
	"Design Superstar",
	"Brand Designer",
	"Brand Specialist",
	"Digtial Samurai",
	"Problem solver",
	"Solutions expert",
	"Designer",
	"Designer and Developer",
	"Creator",
	"Collaborator",
	"Visual Interaction Designer",
	"Artist",
	"Scientific Designer",
	"Digital Product Designer",
	"Maker",
	"Visual Designer",
	"Digital Space Explorer",
	"Creative Designer",
	"Creative Coder",
	"Communicator",
	"Storyteller",
	"Thinker",
	"Doodler",
	"Design Technologist",
	"Creative",
	"Do-er",
	"Multidisciplinary designer",
	"Avid Problem Solver"
];

var job_id = Math.floor(Math.random() * job.length);
$('h3').html(job[job_id]);

var noun = [
	"with a passion for",
	"with a love for",
	"who cares about",
	"with a gift for",
	"specializing in",
	"that loves",
	"who specializes in",
	"who believes in",
	"who evangelizes",
	"focused on",
	"who loves",
	"who enjoys",
	"with an enthusiasm for",
	"who has a passion for",
	"who has a deep love for",
	"who focuses on",
	"with a focus for",
	"passionate about",
	"who strives in"
];

var noun_id = Math.floor(Math.random() * noun.length);
$('h4').html(noun[noun_id]);

var explosion = [
	"positively impacting peoples lives",
	"crafting products and experiences",
	"crafting inspiring experiences",
	"understanding users",
	"uncovering problems",
	"identifing and solving user problems",
	"creating meaningful experiences",
	"creating something that looks good and performs brilliantly",
	"solving design problems",
	"inspiring change",
	"designing",
	"solving complex problems",
	"identifying and understanding",
	"uncovering solutions",
	"building enterprise applications",
	"building mobile applications",
	"powerful and elegant design",
	"positively impacting people on a broad scale",
	"crafting experiences",
	"crafting interfaces",
	"creating products",
	"creating designs",
	"speaking for the users",
	"advocating for the user",
	"problem solving",
	"tackling big problems",
	"driving digital transformation",
	"crafting user-centered experiences",
	"solving people problems",
	"humanizing tech",
	"making it pop",
	"thoughful engaging usability studies",
	"crafting elegant designs",
	"designing intuitive experiences",
	"creating",
	"creating seamless experiences",
	"creating delightful experiences",
	"making",
	"making product experiences",
	"the power of storytelling ",
	"prototyping",
	"research",
	"understanding complex systems"
];

var explosion_id = Math.floor(Math.random() * explosion.length);
$('h5').html(explosion[explosion_id]);

var aftermath = [
	"through design and technology",
	"with care and love",
	"through expert execution",
	"with empathy",
	"through simple, minimal and effective designs",
	"through personal experience, experiments, and research",
	"with meaningful solutions",
	"through easy and delightful experiences",
	"through collaboration",
	"through reflections",
	"across scalable B2B and B2C systems",
	"to benefit people",
	"to benefit users",
	"through UX",
	"through UI",
	"through prototyping",
	"through user testing",
	"through delightful experiences",
	"through design systems",
	"with design systems",
	"with user testing",
	"with UX",
	"with UI",
	"with workshops",
	"with design thinking",
	"with users",
	"with double-diamond methods",
	"with minimalism",
	"with neumorphism",
	"with a human-centered approach",
	"through visual experiences",
	"that progress society"
];

var aftermath_id = Math.floor(Math.random() * aftermath.length);
$('h6').html(aftermath[aftermath_id]);